### ISSUE TITLE
crear index.html

### ISSUE THREAD

**Issue by jdgrafico** [jdgrafico/cocina_facil#1]
crear index en html

**Comment by jdgaravito** [comment]
<link rel="stylesheet" href="myProjects/webProject/icofont/css/icofont.min.css">

**Comment by jdgaravito** [comment]
asdasdas <link rel="stylesheet" href="myProjects/webProject/icofont/css/icofont.min.css">

**Comment by jdgaravito** [comment]
agregar la ruta al head `<link rel="stylesheet" href="myProjects/webProject/icofont/css/icofont.min.css">`

**Comment by jdgaravito** [comment]
la otra es styles.css

**Comment by jdgaravito** [comment]
icofont.min.css
